/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EndpointsRouteImport } from './routes/endpoints'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ServerRouteImport } from './routes/server'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TelegramRouteImport } from './routes/telegram'
import { Route as ApiPublicSplatRouteImport } from './routes/api/public/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointsRoute = EndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerRoute = ServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramRoute = TelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSplatRoute = ApiPublicSplatRouteImport.update({
  id: '/api/public/$',
  path: '/api/public/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/endpoints': typeof EndpointsRoute
  '/explorer': typeof ExplorerRoute
  '/requests': typeof RequestsRoute
  '/security': typeof SecurityRoute
  '/server': typeof ServerRoute
  '/settings': typeof SettingsRoute
  '/telegram': typeof TelegramRoute
  '/api/public/$': typeof ApiPublicSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/endpoints': typeof EndpointsRoute
  '/explorer': typeof ExplorerRoute
  '/requests': typeof RequestsRoute
  '/security': typeof SecurityRoute
  '/server': typeof ServerRoute
  '/settings': typeof SettingsRoute
  '/telegram': typeof TelegramRoute
  '/api/public/$': typeof ApiPublicSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/endpoints': typeof EndpointsRoute
  '/explorer': typeof ExplorerRoute
  '/requests': typeof RequestsRoute
  '/security': typeof SecurityRoute
  '/server': typeof ServerRoute
  '/settings': typeof SettingsRoute
  '/telegram': typeof TelegramRoute
  '/api/public/$': typeof ApiPublicSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/endpoints'
    | '/explorer'
    | '/requests'
    | '/security'
    | '/server'
    | '/settings'
    | '/telegram'
    | '/api/public/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/endpoints'
    | '/explorer'
    | '/requests'
    | '/security'
    | '/server'
    | '/settings'
    | '/telegram'
    | '/api/public/$'
  id:
    | '__root__'
    | '/'
    | '/endpoints'
    | '/explorer'
    | '/requests'
    | '/security'
    | '/server'
    | '/settings'
    | '/telegram'
    | '/api/public/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EndpointsRoute: typeof EndpointsRoute
  ExplorerRoute: typeof ExplorerRoute
  RequestsRoute: typeof RequestsRoute
  SecurityRoute: typeof SecurityRoute
  ServerRoute: typeof ServerRoute
  SettingsRoute: typeof SettingsRoute
  TelegramRoute: typeof TelegramRoute
  ApiPublicSplatRoute: typeof ApiPublicSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoints': {
      id: '/endpoints'
      path: '/endpoints'
      fullPath: '/endpoints'
      preLoaderRoute: typeof EndpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server': {
      id: '/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof ServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram': {
      id: '/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof TelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/$': {
      id: '/api/public/$'
      path: '/api/public/$'
      fullPath: '/api/public/$'
      preLoaderRoute: typeof ApiPublicSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EndpointsRoute: EndpointsRoute,
  ExplorerRoute: ExplorerRoute,
  RequestsRoute: RequestsRoute,
  SecurityRoute: SecurityRoute,
  ServerRoute: ServerRoute,
  SettingsRoute: SettingsRoute,
  TelegramRoute: TelegramRoute,
  ApiPublicSplatRoute: ApiPublicSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
